#!/bin/bash

# Get the C file name from the command line argument
CFILE="$1"

# Get the base name of the C file (without the extension)
BASENAME="${CFILE%.*}"

# Generate the assembly code in Intel syntax using gcc
gcc -S -masm=intel "$CFILE" -o "${BASENAME}.s"
